keys:
  - &nico age1vc3r79rf5mtx7wla0u394lr3nqveqf6edjwe0fmf0s7umncyqaaqjl9w78
  - &oracle-dragon age1npmc4l8gph7nqrkq737faqhgcmt79spuzjdryvzvdymngwxdfujsfeq3pm
  - &rpi-dragon age19gle3kmstnprnagmasp3ul9yvcy0qa3rrdvzz57ar4l8naqfryvqs2mnka
  - &slim-lair age1amrvulahe6tayc9d054pvfyk0wr4psekjj05p27fdav7m6x34fzsqd6e5l
  - &tv-nixos age1g8hzfc2heln349ah2fykv8fwq6hlxwvveu6rx6vq82e5tx6l8ygsa0gnxq

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *nico
          - *oracle-dragon
          - *rpi-dragon
          - *slim-lair
          - *tv-nixos
