version: "3"

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest-arm64v8
    container_name: rustdesk_hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    command: hbbs
    environment:
      ENCRYPTED_ONLY: 1
      RELAY_SERVERS: "rd.dr460nf1r3.org:21117"
    volumes:
      - ./rustdesk:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:latest-arm64v8
    container_name: rustdesk_hbbr
    ports:
      - 21117:21117
      - 21119:21119
    environment:
      ENCRYPTED_ONLY: 1
      RELAY_SERVERS: "rd.dr460nf1r3.org:21117"
    command: hbbr
    volumes:
      - ./rustdesk:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
