name: "Build images"

on:
  pull_request_target:
    types: [labeled]
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Periodic flake bump"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "system-features = big-parallel kvm\naccept-flake-config = true"
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - run: bash ./ci/build_images.sh
