name: "Build config"

on:
  pull_request:
  push:
  workflow_call:

jobs:
  build-cachix-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = big-parallel kvm
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          name: dr460nf1r3
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - run: cd ./ci; bash ./push_to_cachix.sh
